### ISSUE TITLE
allow_list: or block_list: don't appear to being processed from the configuration.yaml correctly

### ISSUE THREAD

**Issue by brucemiranda** [zxdavb/evohome_cc#27]
```
Logger: custom_components.evohome_cc
Source: custom_components/evohome_cc/__init__.py:62
Integration: Honeywell RF (RAMSES II protocol) (documentation, issues)
First occurred: 4:31:51 PM (1 occurrences)
Last logged: 4:31:51 PM

evohome_cc v0.7.1, using evohome_rf v0.7.1 - versions match (this is good)
```

Even if allow_list is specified, I get a message 

```
Logger: evohome_rf.transport
Source: /usr/local/lib/python3.8/site-packages/evohome_rf/transport.py:323
First occurred: 4:15:47 PM (1 occurrences)
Last logged: 4:15:47 PM
Not Using an device filter (an allow_list is recommended)
```

If block_list is specified, I get a message

```
Logger: evohome_rf.schema
Source: /usr/local/lib/python3.8/site-packages/evohome_rf/schema.py:263
First occurred: 4:15:47 PM (1 occurrences)
Last logged: 4:15:47 PM
An empty blocklist was configured, so will be ignored
```

If both a specified, then I get a correct message that both cannot be specified. But nothing in my allow_list of block_list appears to being processed. 
Here is my configuration.yaml 

```
evohome_cc:
  scan_interval: 60
  serial_port: rfc2217://localhost:5001
  config:
    packet_log: evohome/packet.log
  schema:
    controller: 01:078710
  allow_list:
    - 10:067219
    - 07:017494
    - 13:109598
    - 04:133277
    - 04:057586
    - 22:032844
    - 22:060293
    - 13:114333
    - 04:061731
    - 34:103601
    - 04:061402
    - 04:187989
    - 34:147397
    - 04:061760
    - 34:103839
    - 04:098464
    - 04:098306
    - 04:098474
    - 04:098449
    - 04:098455
#  block_list:
#    - 12:106131
#    - 13:031200
#    - 13:050361
#    - 13:031208
#    - 13:101853
#    - 13:125302
#    - 13:144830
#    - 13:133379
#    - 22:055075
#    - 22:068154
#    - 22:006688
#    - 22:054901
#    - 22:068254
#    - 31:118732
#    - 31:011364
```

**Comment by brucemiranda** [comment]
Even with the enforce_allowlist: true my allow_list is not being processed by evohome_cc

```
evohome_cc:
  scan_interval: 60
  serial_port: rfc2217://localhost:5001
  config:
    enforce_allowlist: true
    packet_log: evohome/packet.log
  schema:
    controller: 01:078710
  allow_list:
    - 10:067219
    - 07:017494
    - 13:109598
    - 04:133277
    - 04:057586
    - 22:032844
    - 22:060293
    - 13:114333
    - 04:061731
    - 34:103601
    - 04:061402
    - 04:187989
    - 34:147397
    - 04:061760
    - 34:103839
    - 04:098464
    - 04:098306
    - 04:098474
    - 04:098449
    - 04:098455
```

Tried enforce_blocklist: true but apparently that is not a valid configuration setting.
