### ISSUE TITLE
Invalid config for [evohome_cc]: required key not provided

### ISSUE THREAD

**Issue by djcelvin** [zxdavb/evohome_cc#9]
I encounter an issue with this cc for a few days.
I tried re-install of the cc via HACS, HAOS is up to date (5.11), and last releases.

The full error message : Invalid config for [evohome_cc]: required key not provided @ data['evohome_cc']['config']. Got None. 

Extract of my configuration.yaml : 

evohome_cc:
  scan_interval: 60
  serial_port: /dev/serial/by-id/usb-Texas_Instruments_TUSB3410_Boot_Device_TUSB3410-if00-port0
  schema:
      controller: 01:xxxxxx

If I add the packet_log attribute, i got this error : Invalid config for [evohome_cc]: [packet_log] is an invalid option for [evohome_cc]. Check: evohome_cc->evohome_cc->packet_log.

**Comment by iMiMx** [comment]
This works - you need to specify config and packet_log

```
evohome_cc:
  scan_interval: 60
  serial_port: /dev/serial/by-id/usb-SHK_NANO_CUL_868-if00-port0
  config:
    packet_log: /config/packet.log
  schema:
    controller: 01:xxxxxx
#  ignore_list:
```
